cask_args appdir: '/Applications'

# Add taps
tap 'caskroom/cask'
tap 'pivotal/tap'

# Python
# (see https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites)
brew 'pipenv'
brew 'pyenv'
brew 'readline'
brew 'xz'

# Javascript
brew 'node'
brew 'yarn'

# Java
cask 'java'
brew 'maven'
brew 'springboot'

# Database
brew 'postgresql'

# CLI Utilities
brew 'coreutils'
brew 'curl'
brew 'htop'
brew 'httpie'
brew 'iperf3'
brew 'mtr'
cask 'ngrok'
brew 'tree'
brew 'wget'
brew 'zsh'

# Softwares
cask 'clamxav'
cask 'dash'
cask 'docker'
cask 'figma'
cask 'google-chrome'
cask 'google-drive'
cask 'hex-fiend'
cask 'iterm2-beta'
cask 'jetbrains-toolbox'
cask 'little-snitch'
cask 'macpass'
cask 'mactex'
cask 'notion'
cask 'spectacle'
cask 'sublime-text'
cask 'telegram-desktop'
cask 'typora'
cask 'vlc'
cask 'whatsapp'