cask_args appdir: '/Applications'

# Add taps
tap 'caskroom/cask'

# Python
# (see https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites)
brew 'pipenv'
brew 'pyenv'
brew 'readline'
brew 'xz'

# CLI Utilities
brew 'coreutils'
brew 'curl'
brew 'htop'
brew 'httpie'
brew 'iperf3'
brew 'mtr'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# Softwares
cask 'dash'
cask 'dropbox'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'hex-fiend'
cask 'iterm2'
cask 'little-snitch'
cask 'macpass'
cask 'sublime-text'
cask 'spectacle'
cask 'telegram-desktop'
cask 'vlc'
