#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# find the installers and run them
cd "$(dirname $0)"/..

echo "› Run all installers"
find . -name install.sh 
printf "\n"

echo "› Start"
find . -name install.sh -exec sh -c "{}" \;
