#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# Run Homebrew through the Brewfile
cd "$(dirname $0)"/../homebrew
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
cd "$(dirname $0)"/..
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
